Gerenciamento de Reservas
regis-amaral/ProjetoRavin pull request #63
Opened 2023-07-30 21:58 UTC by tiagospeckart

# Sistema de Reservas implementado

## Implementado
- #57 
- #58 
- #59 
- #60 
- #61

## Nota

Acabei esquecendo de trocar de branch, então por isso to repetindo o issue.

2023-07-31 13:49 UTC, regis-amaral requested changes
### observação 1

Ao tentar rodar o programa recebi um erro:
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.ravin.App.mainMenu(App.java:34)
        at org.ravin.App.main(App.java:21)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:209)
        at org.ravin.views.View.<clinit>(View.java:8)

Acredito que seja pela modificação do local da logo do ravin: View.java:8, como a imagem não está no mesmo nível de diretório da View.java, é preciso ir voltando o diretório através da adição de ''../' até que que ele encontre a imagem. Usar "../../../images/logo.png" funcionou pra mim.

---
### Observação 2

Percebi que a estrutura de pastas foi modificada em algum momento em commits anteriores, talvez até em branchs anteriores, pois já esta assim na dev:
![image](https://github.com/RavinProject/ProjetoRavin/assets/118540708/e327af7e-61e8-47eb-88fa-95cb133d0f6f)

---
### observação 3

App.java:
exceptions devem ser tratadas dentro do método que chamar outros métodos que podem as gerar, nunca na main, pois nesse caso, se ocorrerem irão parar a execução do programa.
Sei que há casos de exemplificação que aparerecem dessa forma, mas acredito que sejam apenas para ser mais didático e poupar mais linhas de código para o leitor.

---
### observação 4

Ao tentar cadastrar uma mesa recebi o segfuinte erro:
java.lang.NullPointerException: Cannot invoke "org.ravin.models.Funcionario.getNome()" because the return value of "org.ravin.models.Mesa.getFuncionario()" is null
        at org.ravin.views.mesa.SubmenuMesa.imprimeMesa(SubmenuMesa.java:56)
        at org.ravin.views.mesa.CadastrarMesaView.cadastrarMesa(CadastrarMesaView.java:31)
        at org.ravin.views.mesa.SubmenuMesa.menuMesa(SubmenuMesa.java:27)
        at org.ravin.App.processaOpcaoMenu(App.java:60)
        at org.ravin.App.mainMenu(App.java:39)
        at org.ravin.App.main(App.java:21)

Acho que colocando um teste na linha SubmenuMesa.java:56 pra checar se há um funcionário e em caso contrário omitir a informação, já resolve;

---
### observação 5

Um problema semelhante a observação 4 ocorre ao selecionar a opção listar mesas e entre a lista de mesas existir uma sem funcionário:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.ravin.models.Funcionario.getNome()" because the return value of "org.ravin.models.Mesa.getFuncionario()" is null
        at org.ravin.views.mesa.RecuperarMesaView.listarMesas(RecuperarMesaView.java:31)
        at org.ravin.views.mesa.SubmenuMesa.menuMesa(SubmenuMesa.java:30)
        at org.ravin.App.processaOpcaoMenu(App.java:60)
        at org.ravin.App.mainMenu(App.java:39)
        at org.ravin.App.main(App.java:21)

---
### observação 6

Em que momento se insere um funcionário a uma mesa?

Existe a possibilidade de trocar o funcionário de uma mesa?

---
### observação 7

Pouco relevante, mas na CadastrarReservaView linha 52, no caso de um cliente não ser encontrado o ideal é exibir a mensagem retornada pela controller.

---
### observação 8

Ao tentar inserir uma reserva obtive um erro que encerrou a aplicação:
![image](https://github.com/RavinProject/ProjetoRavin/assets/118540708/9f73cd4f-484b-423e-839f-2bf0993481b6)

2023-07-31 13:49 UTC, regis-amaral commented on src/main/java/org/ravin/App.java
@tiagospeckart as possíveis exceptions devem ser tratadas dentro do método que chamar outros métodos que podem as gerar, nunca na main, pois nesse caso, se ocorrerem irão parar a execução do programa. 
Sei que há casos de exemplificação que aparerecem dessa forma, mas acredito que sejam apenas para ser mais didático e poupar mais linhas de código para o leitor.

2023-07-31 18:14 UTC, tiagospeckart commented on src/main/java/org/ravin/App.java
> +    private static void mainMenu() throws EntidadeNaoEncontradaException, MesaNaoDisponivelException {
```suggestion
    private static void mainMenu() {
```

2023-07-31 18:15 UTC, tiagospeckart commented on src/main/java/org/ravin/App.java
> +    private static boolean processaOpcaoMenu(String opcao) throws EntidadeNaoEncontradaException, MesaNaoDisponivelException {
```suggestion
    private static boolean processaOpcaoMenu(String opcao) {
```

2023-07-31 18:17 UTC, tiagospeckart commented on src/main/java/org/ravin/controllers/ClienteController.java
>          Optional<Cliente> cliente = clienteService.recuperarPorId(id);
```suggestion
        Optional<Cliente> oCliente = clienteService.recuperarPorId(id);
        if (oCliente.isPresent()) {
            return oMesa.get();
        } else {
            throw new EntidadeNaoEncontradaException("Cliente não encontrado para o ID: " + id);
        }
```

2023-07-31 18:39 UTC, tiagospeckart commented
> ### observação 1
> Ao tentar rodar o programa recebi um erro: Exception in thread "main" java.lang.ExceptionInInitializerError at org.ravin.App.mainMenu(App.java:34) at org.ravin.App.main(App.java:21) Caused by: java.lang.NullPointerException at java.base/java.util.Objects.requireNonNull(Objects.java:209) at org.ravin.views.View.(View.java:8)

> Acredito que seja pela modificação do local da logo do ravin: View.java:8, como a imagem não está no mesmo nível de diretório da View.java, é preciso ir voltando o diretório através da adição de ''../' até que que ele encontre a imagem. Usar "../../../images/logo.png" funcionou pra mim.

Beleza, nesse basta arrumar o path.

> ### Observação 2
> Percebi que a estrutura de pastas foi modificada em algum momento em commits anteriores, talvez até em branchs anteriores, pois já esta assim na dev: ![image](https://user-images.githubusercontent.com/118540708/257226259-e327af7e-61e8-47eb-88fa-95cb133d0f6f.png)

Essa interface tinha acabado sobrando em algum commit mesmo, mas foi deletado nessa Issue

> ### observação 3
> App.java: exceptions devem ser tratadas dentro do método que chamar outros métodos que podem as gerar, nunca na main, pois nesse caso, se ocorrerem irão parar a execução do programa. Sei que há casos de exemplificação que aparerecem dessa forma, mas acredito que sejam apenas para ser mais didático e poupar mais linhas de código para o leitor.

Pois é, nesse caso eu tava me atrapalhando com a IDE, pois declarei uma Exception nova para uma mesa cheia, mas não tinha alocado onde ela seria tradada. Clicando em sugestões da IDE a Exception acabou subindo até a main. Oops!

> ### observação 4
> Ao tentar cadastrar uma mesa recebi o segfuinte erro: java.lang.NullPointerException: Cannot invoke "org.ravin.models.Funcionario.getNome()" because the return value of "org.ravin.models.Mesa.getFuncionario()" is null at org.ravin.views.mesa.SubmenuMesa.imprimeMesa(SubmenuMesa.java:56) at org.ravin.views.mesa.CadastrarMesaView.cadastrarMesa(CadastrarMesaView.java:31) at org.ravin.views.mesa.SubmenuMesa.menuMesa(SubmenuMesa.java:27) at org.ravin.App.processaOpcaoMenu(App.java:60) at org.ravin.App.mainMenu(App.java:39) at org.ravin.App.main(App.java:21)
> 
> Acho que colocando um teste na linha SubmenuMesa.java:56 pra checar se há um funcionário e em caso contrário omitir a informação, já resolve;

Pois então! Eu tinha deixado a alocação de Funcionário para um momento posterior, separando a criação da mesa de um sistema de alocação de funcionário. O problema é que faltou implementar esses sistema. Vou criar uma Issue pra isso

> ### observação 5
> Um problema semelhante a observação 4 ocorre ao selecionar a opção listar mesas e entre a lista de mesas existir uma sem funcionário:
> 
> Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.ravin.models.Funcionario.getNome()" because the return value of "org.ravin.models.Mesa.getFuncionario()" is null at org.ravin.views.mesa.RecuperarMesaView.listarMesas(RecuperarMesaView.java:31) at org.ravin.views.mesa.SubmenuMesa.menuMesa(SubmenuMesa.java:30) at org.ravin.App.processaOpcaoMenu(App.java:60) at org.ravin.App.mainMenu(App.java:39) at org.ravin.App.main(App.java:21)

Talvez nesse caso, o retorno poderia ser nulo, já que nem toda mesa precisa ter um funcionário alocado. Isso é tranquilo de corrigir.

> ### observação 6
> Em que momento se insere um funcionário a uma mesa?
> 
> Existe a possibilidade de trocar o funcionário de uma mesa?

O mesmo que o comentário da observação 4.

> ### observação 7
> Pouco relevante, mas na CadastrarReservaView linha 52, no caso de um cliente não ser encontrado o ideal é exibir a mensagem retornada pela controller.

Relevante sim! Já que não temos retornos HTTP, a essência dos controllers é servirem para disparar erros informativos.

> ### observação 8
> Ao tentar inserir uma reserva obtive um erro que encerrou a aplicação: ![image](https://user-images.githubusercontent.com/118540708/257240378-9f73cd4f-484b-423e-839f-2bf0993481b6.png)

Esse último bug...meu deus kkkk

---

Obrigado pelo review detalhado!

2023-07-31 21:30 UTC, tiagospeckart commented on README.md
> +4. Execute a classe principal:
```suggestion
5. Execute a classe principal:
```

2023-08-01 00:20 UTC, tiagospeckart commented on src/main/java/org/ravin/App.java
Resolvido adicionando try/catch nas views de CriarReserva

2023-08-01 00:26 UTC, tiagospeckart reviewed
Resolvido:
- Exceções vazando para Main
- Lidar com erros em `src/main/java/org/ravin/views/reserva/CadastrarReservaView.java`
- Posto tratamento de erro em inserir() de ReservaController
- Reserva Service agora lida com 3 tipos de erros distintos, dependendo do tipo de situação que a mesa se encontra
- Loop infinito em inserir() de Mesa
- Exibir mesa caso Funcionário seja nulo (erro de nullpointer)

2023-08-01 21:37 UTC, regis-amaral approved these changes

2023-08-02 00:21 UTC, merged